### ISSUE TITLE
Allow progress to be resumed for existing download

### ISSUE THREAD

**Issue by markst** [t-osawa-009/AssetDownloadWrapper#4]
Since `progressHandler` is a private property closure, it is not possible to continue observing download progress if for whatever reason the existing observer no longer exists.

**Comment by markst** [comment]
An example of this is if a view controller is popped off a navigation stack, but a new instance is pushed the the stack. It would be great to identify if a download is already in progress & start observing the existing download.

**Comment by markst** [comment]
Perhaps this could be achieved by looking up the `activeDownloadsDictionary` rather than exposing the `progressHandler` & `downloadHandler` properties? 

```swift
public func download(asset: AssetWrapper,
                     options: [String : Any]? = AssetDownloadManager.options,
                     progressHandler: ((_ asset: AssetWrapper, _ progress: CGFloat) -> Void)? = nil,
                     completion: ((Result<AssetWrapper, Error>) -> Void)? = nil) {
    if let task = activeDownloadsDictionary.first(where: { $0.value == asset }) {
        self.downloadHandler = completion
        self.progressHandler = progressHandler
        return
    }
```

**Comment by t-osawa-009** [comment]
OK
